

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "ROC.web\Web.config"
//     Connection String Name: "RocContext"
//     Connection String:      "Data Source=(local);Initial Catalog=roc_wms;Integrated Security=True;Application Name=MyApp"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Express Edition
// Database Engine Edition: Express

namespace ROC.BLL
{
    using ROC.Modles;
    using ROC.DAL;

    #region IService
    public partial interface IActionInfoService:IBaseService<ActionInfo>
    {
    }
    public partial interface IMenuClassService:IBaseService<MenuClass>
    {
    }
    #endregion  

    #region Service
    public partial class ActionInfoService:BaseService<ActionInfo>,IActionInfoService
    {
        public override bool SetCurrentRepository()
        {
            this.CurrentRepository = DbSessionContext.ActionInfoRepository;
            this.AddDisposableObject(this.CurrentRepository);
            return true;
        }
    }
    public partial class MenuClassService:BaseService<MenuClass>,IMenuClassService
    {
        public override bool SetCurrentRepository()
        {
            this.CurrentRepository = DbSessionContext.MenuClassRepository;
            this.AddDisposableObject(this.CurrentRepository);
            return true;
        }
    }
    #endregion
  
}
