

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
// 
// Do not make changes directly to this file - edit the template instead.
// 
// The following connection settings were used to generate this file:
//     Configuration file:     "ROC.web\Web.config"
//     Connection String Name: "RocContext"
//     Connection String:      "Data Source=(local);Initial Catalog=roc_wms;user=sa;password=**zapped**;;Application Name=MyApp;MultipleActiveResultSets=True"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Express Edition
// Database Engine Edition: Express

namespace ROC.DAL
{
    using ROC.Modles;
    using System.Data.SqlClient;
    using System.Data.Entity;

    #region IRepository  czp modify 
    public partial interface IActionInfoRepository:IBaseRepository<ActionInfo>
    {
    }
    public partial interface IMenuRepository:IBaseRepository<Menu>
    {
    }
    public partial interface IMenuClassRepository:IBaseRepository<MenuClass>
    {
    }
    public partial interface IRoleRepository:IBaseRepository<Role>
    {
    }
    public partial interface IRoleActionInfoRepository:IBaseRepository<RoleActionInfo>
    {
    }
    public partial interface IUserRepository:IBaseRepository<User>
    {
    }
    public partial interface IUserRoleRepository:IBaseRepository<UserRole>
    {
    }
    #endregion   

    #region Repository
    public partial class ActionInfoRepository:BaseRepository<ActionInfo>,IActionInfoRepository
    {
    }
    public partial class MenuRepository:BaseRepository<Menu>,IMenuRepository
    {
    }
    public partial class MenuClassRepository:BaseRepository<MenuClass>,IMenuClassRepository
    {
    }
    public partial class RoleRepository:BaseRepository<Role>,IRoleRepository
    {
    }
    public partial class RoleActionInfoRepository:BaseRepository<RoleActionInfo>,IRoleActionInfoRepository
    {
    }
    public partial class UserRepository:BaseRepository<User>,IUserRepository
    {
    }
    public partial class UserRoleRepository:BaseRepository<UserRole>,IUserRoleRepository
    {
    }
    #endregion

    public interface IDbSession
        {
        
            IActionInfoRepository ActionInfoRepository { get; set; }
        
            IMenuRepository MenuRepository { get; set; }
        
            IMenuClassRepository MenuClassRepository { get; set; }
        
            IRoleRepository RoleRepository { get; set; }
        
            IRoleActionInfoRepository RoleActionInfoRepository { get; set; }
        
            IUserRepository UserRepository { get; set; }
        
            IUserRoleRepository UserRoleRepository { get; set; }
    
            /// <summary>
            /// 保存所有改变
            /// </summary>
            /// <returns></returns>
            int SaveChanges();
            /// <summary>
            /// 执行sql语句
            /// </summary>
            /// <param name="sql"></param>
            /// <param name="paras"></param>
            /// <returns></returns>
            int ExecuteSql(string sql, params SqlParameter[] paras);
        }

    public class DbSession:IDbSession
        {

        
            private IActionInfoRepository _ActionInfoRepository;
            public IActionInfoRepository ActionInfoRepository
            {
                get
                {
                    if (_ActionInfoRepository == null)
                    {
                        _ActionInfoRepository = new ActionInfoRepository();
                    }
                    return _ActionInfoRepository;
                }
                set
                {
                    _ActionInfoRepository = value;
                }
            }
        
            private IMenuRepository _MenuRepository;
            public IMenuRepository MenuRepository
            {
                get
                {
                    if (_MenuRepository == null)
                    {
                        _MenuRepository = new MenuRepository();
                    }
                    return _MenuRepository;
                }
                set
                {
                    _MenuRepository = value;
                }
            }
        
            private IMenuClassRepository _MenuClassRepository;
            public IMenuClassRepository MenuClassRepository
            {
                get
                {
                    if (_MenuClassRepository == null)
                    {
                        _MenuClassRepository = new MenuClassRepository();
                    }
                    return _MenuClassRepository;
                }
                set
                {
                    _MenuClassRepository = value;
                }
            }
        
            private IRoleRepository _RoleRepository;
            public IRoleRepository RoleRepository
            {
                get
                {
                    if (_RoleRepository == null)
                    {
                        _RoleRepository = new RoleRepository();
                    }
                    return _RoleRepository;
                }
                set
                {
                    _RoleRepository = value;
                }
            }
        
            private IRoleActionInfoRepository _RoleActionInfoRepository;
            public IRoleActionInfoRepository RoleActionInfoRepository
            {
                get
                {
                    if (_RoleActionInfoRepository == null)
                    {
                        _RoleActionInfoRepository = new RoleActionInfoRepository();
                    }
                    return _RoleActionInfoRepository;
                }
                set
                {
                    _RoleActionInfoRepository = value;
                }
            }
        
            private IUserRepository _UserRepository;
            public IUserRepository UserRepository
            {
                get
                {
                    if (_UserRepository == null)
                    {
                        _UserRepository = new UserRepository();
                    }
                    return _UserRepository;
                }
                set
                {
                    _UserRepository = value;
                }
            }
        
            private IUserRoleRepository _UserRoleRepository;
            public IUserRoleRepository UserRoleRepository
            {
                get
                {
                    if (_UserRoleRepository == null)
                    {
                        _UserRoleRepository = new UserRoleRepository();
                    }
                    return _UserRoleRepository;
                }
                set
                {
                    _UserRoleRepository = value;
                }
            }
    
            public int SaveChanges()
            {
                IDbContextFactory dbFactory = new DbContextFactory();
                DbContext db = dbFactory.GetCurrentThreadInstance();
                return db.SaveChanges();
            }

            public int ExecuteSql(string sql, params System.Data.SqlClient.SqlParameter[] paras)
            {
                IDbContextFactory dbFactory = new DbContextFactory();
                DbContext db = dbFactory.GetCurrentThreadInstance();
                return db.Database.ExecuteSqlCommand(sql, paras);
            }
        }
}
